# Workflow to build, sign, compress, and upload binaries to a release
name: Build and Release

on:
  push:
    branches: [ naprakas/AutomateBuildProcess ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    env:
      version: 1.0.0

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Publish binaries for each target runtime
    - name: Publish Binaries
      run: |
        dotnet publish Source/RealTimeKql/RealTimeKql.csproj -r win-x64 -f netcoreapp3.1 -c Release /p:PublishSingleFile=true --self-contained false --output ${{ runner.temp }}\win-x64
        dotnet publish Source/RealTimeKql/RealTimeKql.csproj -r linux-x64 -f netcoreapp3.1 -c Release /p:PublishSingleFile=true --self-contained false --output ${{ runner.temp }}\linux-x64

    # Sign binaries for Windows
    - name: Sign Binaries
      uses: ./Source/Actions/SignAction
      with:
        certificate: '${{ secrets.BASE64_ENCODED_PFX }}'
        key: '${{ secrets.PFX_KEY }}'
        directory: '${{ runner.temp }}\win-x64'
    
    # Compress binaries for each target runtime
    - name: Compress Binaries Windows
      run: |
        mkdir ${{ github.workspace }}\ReleaseAssets
        copy Doc/Queries/Windows/* ${{ runner.temp }}\win-x64
        Compress-Archive -Path ${{ runner.temp }}\win-x64\* -DestinationPath "${{ github.workspace }}\ReleaseAssets\RealTimeKql.v${{ env.version }}.zip"
        copy Doc/Queries/Linux/* ${{ runner.temp }}\linux-x64
        cd ReleaseAssets
        tar -czvf "RealTimeKql.v${{ env.version }}.tar.gz" ${{ runner.temp }}\linux-x64\*
        dir "RealTimeKql.v${{ env.version }}.*"